name: bank
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  excel: ^2.0.6
  path_provider: ^2.0.13
  google_fonts: ^5.1.0
  permission_handler: ^11.0.1
  open_file: ^3.3.3
  file_picker: ^6.2.1
  shared_preferences: ^2.2.3 # Added shared_preferences dependency
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  device_info_plus: ^9.1.2
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true